# Generated by Django 6.1 on 2026-08-31 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
