# Generated by Django 6.1 on 2026-09-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_course'),
        ('students', '0002_student_address'),
    ]

    operations = [
    ]
